## Analyzing New York's Yellow taxi dataset

- The datasets can be accessed from [here](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
- Time period: `January 2022 - December 2025`
- visit [`here`](https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page) to know what each column means
- Dataset Characteristics <br>
 -> File Format: Parquet  
 -> Dataset type: Tabular  
 -> Number of columns: 19. 
 -> Time Period: 4 years (January - December)
-> 2022:
-> 2023:
-> 2024:
-> 2025:

In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('../raw/2022/yellow_tripdata_2022-01.parquet')

In [3]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-01-01 00:35:40,2022-01-01 00:53:29,2.0,3.80,1.0,N,142,236,1,14.50,3.0,0.5,3.65,0.0,0.3,21.95,2.5,0.0
1,1,2022-01-01 00:33:43,2022-01-01 00:42:07,1.0,2.10,1.0,N,236,42,1,8.00,0.5,0.5,4.00,0.0,0.3,13.30,0.0,0.0
2,2,2022-01-01 00:53:21,2022-01-01 01:02:19,1.0,0.97,1.0,N,166,166,1,7.50,0.5,0.5,1.76,0.0,0.3,10.56,0.0,0.0
3,2,2022-01-01 00:25:21,2022-01-01 00:35:23,1.0,1.09,1.0,N,114,68,2,8.00,0.5,0.5,0.00,0.0,0.3,11.80,2.5,0.0
4,2,2022-01-01 00:36:48,2022-01-01 01:14:20,1.0,4.30,1.0,N,68,163,1,23.50,0.5,0.5,3.00,0.0,0.3,30.30,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2463926,2,2022-01-31 23:36:53,2022-01-31 23:42:51,NaN,1.32,NaN,NaN,90,170,0,8.00,0.0,0.5,2.39,0.0,0.3,13.69,NaN,NaN
2463927,2,2022-01-31 23:44:22,2022-01-31 23:55:01,NaN,4.19,NaN,NaN,107,75,0,16.80,0.0,0.5,4.35,0.0,0.3,24.45,NaN,NaN
2463928,2,2022-01-31 23:39:00,2022-01-31 23:50:00,NaN,2.10,NaN,NaN,113,246,0,11.22,0.0,0.5,2.00,0.0,0.3,16.52,NaN,NaN
2463929,2,2022-01-31 23:36:42,2022-01-31 23:48:45,NaN,2.92,NaN,NaN,148,164,0,12.40,0.0,0.5,0.00,0.0,0.3,15.70,NaN,NaN
2463930,2,2022-01-31 23:46:00,2022-02-01 00:13:00,NaN,8.94,NaN,NaN,186,181,0,25.48,0.0,0.5,6.28,0.0,0.3,35.06,NaN,NaN

In [4]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
count,2.463931e+06,2463931,2463931,2.392428e+06,2.463931e+06,2.392428e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.463931e+06,2.392428e+06,2.392428e+06
mean,1.707819e+00,2022-01-17 01:19:51.689724,2022-01-17 01:34:04.421902,1.389453e+00,5.372751e+00,1.415507e+00,1.660768e+02,1.635807e+02,1.194449e+00,1.294648e+01,1.006710e+00,4.914539e-01,2.385696e+00,3.749773e-01,2.967234e-01,1.916937e+01,2.282322e+00,8.249935e-02
min,1.000000e+00,2008-12-31 22:23:09,2008-12-31 23:06:56,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-4.800000e+02,-4.500000e+00,-5.000000e-01,-1.252200e+02,-3.140000e+01,-3.000000e-01,-4.803000e+02,-2.500000e+00,-1.250000e+00
25%,1.000000e+00,2022-01-09 15:37:41,2022-01-09 15:50:50.500000,1.000000e+00,1.040000e+00,1.000000e+00,1.320000e+02,1.130000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,7.200000e-01,0.000000e+00,3.000000e-01,1.130000e+01,2.500000e+00,0.000000e+00
50%,2.000000e+00,2022-01-17 12:11:45,2022-01-17 12:23:49,1.000000e+00,1.740000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.000000e+00,5.000000e-01,5.000000e-01,2.000000e+00,0.000000e+00,3.000000e-01,1.469000e+01,2.500000e+00,0.000000e+00
75%,2.000000e+00,2022-01-24 13:49:37.500000,2022-01-24 14:02:51,1.000000e+00,3.130000e+00,1.000000e+00,2.340000e+02,2.360000e+02,1.000000e+00,1.400000e+01,2.500000e+00,5.000000e-01,3.000000e+00,0.000000e+00,3.000000e-01,2.002000e+01,2.500000e+00,0.000000e+00
max,6.000000e+00,2022-05-18 20:41:57,2022-05-18 20:47:45,9.000000e+00,3.061593e+05,9.900000e+01,2.650000e+02,2.650000e+02,5.000000e+00,4.010923e+05,3.350000e+01,1.659000e+01,8.888800e+02,1.933000e+02,3.000000e-01,4.010956e+05,2.500000e+00,1.250000e+00
std,5.021375e-01,NaN,NaN,9.829686e-01,5.478714e+02,5.917573e+00,6.546806e+01,7.079016e+01,5.001778e-01,2.558149e+02,1.236226e+00,8.291560e-02,2.830698e+00,1.680538e+00,4.374741e-02,2.559641e+02,7.432040e-01,3.125554e-01

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2463931 entries, 0 to 2463930
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), str(1)
memory usage: 359.7 MB

## Columns and Defenitions

* `VendorID`: A code indicating the TPEP provider that provided the record. <br>
-> 1 = Creative Mobile Technologies, LLC  
-> 2 = Curb Mobility, LLC  
-> 6 = Myle Technologies Inc  
-> 7 = Helix  

* `tpep_pickup_datetime`: The date and time when the meter was engaged.
* `tpep_dropoff_datetime`: The date and time when the meter was disengaged.
* `passenger_count`: The number of passengers in the vehicle.
* `trip_distance`: The elapsed trip distance in miles reported by the taximeter.
* `RatecodeID`: The final rate code in effect at the end of the trip. <br>
-> 1 = Standard rate  
-> 2 = JFK  
-> 3 = Newark  
-> 4 = Nassau or Westchester  
-> 5 = Negotiated fare  
-> 6 = Group ride  
-> 99 = Null/unknown  
* `store_and_fwd_flag`: This flag indicates whether the trip record was held in vehicle memory before
sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server. <br>
-> Y = store and forward trip  
-> N = not a store and forward trip  
* `PULocationID`: TLC Taxi Zone in which the taximeter was engaged.
* `DOLocationID`: TLC Taxi Zone in which the taximeter was disengaged.
* `payment_type`: A numeric code signifying how the passenger paid for the trip. <br>
-> 0 = Flex Fare trip  
-> 1 = Credit card  
-> 2 = Cash  
-> 3 = No charge  
-> 4 = Dispute  
-> 5 = Unknown  
-> 6 = Voided trip  
* `fare_amount`: The time-and-distance fare calculated by the meter.
* `extra`: Miscellaneous extras and surcharges.
* `mta_tax`: Tax that is automatically triggered based on the metered rate in use.
* `tip_amount`: Tip amount – This field is automatically populated for credit card tips. Cash tips are not included.
* `tolls_amount`: Total amount of all tolls paid in trip
* `improvement_surcharge`: Improvement surcharge assessed trips at the flag drop
* `total_amount`: The total amount charged to passengers. Does not include cash tips. (Total amount is the sum of `fare_amount`, `extra`, `mta_tax`, `tip_amount`, `tolls_amount`, and `improvement_surcharge`)
* `congestion_surcharge`: Total amount collected in trip for NYS congestion surcharge.
* `airport_fee`: For pick up only at LaGuardia and John F. Kennedy Airports
* `cbd_congestion_fee`: Per-trip charge for MTA's Congestion Relief Zone starting Jan. 5, 2025.

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-01-01 00:35:40,2022-01-01 00:53:29,2.0,3.80,1.0,N,142,236,1,14.5,3.0,0.5,3.65,0.0,0.3,21.95,2.5,0.0
1,1,2022-01-01 00:33:43,2022-01-01 00:42:07,1.0,2.10,1.0,N,236,42,1,8.0,0.5,0.5,4.00,0.0,0.3,13.30,0.0,0.0
2,2,2022-01-01 00:53:21,2022-01-01 01:02:19,1.0,0.97,1.0,N,166,166,1,7.5,0.5,0.5,1.76,0.0,0.3,10.56,0.0,0.0
3,2,2022-01-01 00:25:21,2022-01-01 00:35:23,1.0,1.09,1.0,N,114,68,2,8.0,0.5,0.5,0.00,0.0,0.3,11.80,2.5,0.0
4,2,2022-01-01 00:36:48,2022-01-01 01:14:20,1.0,4.30,1.0,N,68,163,1,23.5,0.5,0.5,3.00,0.0,0.3,30.30,2.5,0.0

## Using DuckDB for quering through the data

In [7]:
import duckdb

In [8]:
df = duckdb.read_parquet('../raw/*/*.parquet')

In [9]:
df.columns

['VendorID',
 'tpep_pickup_datetime',
 'tpep_dropoff_datetime',
 'passenger_count',
 'trip_distance',
 'RatecodeID',
 'store_and_fwd_flag',
 'PULocationID',
 'DOLocationID',
 'payment_type',
 'fare_amount',
 'extra',
 'mta_tax',
 'tip_amount',
 'tolls_amount',
 'improvement_surcharge',
 'total_amount',
 'congestion_surcharge',
 'airport_fee']

In [10]:
df = duckdb.sql("""
                SELECT * EXCLUDE (
                VendorID,
                store_and_fwd_flag
                )
                FROM df
                """)

In [11]:
df

┌──────────────────────┬───────────────────────┬─────────────────┬───────────────┬────────────┬──────────────┬──────────────┬──────────────┬─────────────┬────────┬─────────┬────────────┬──────────────┬───────────────────────┬──────────────┬──────────────────────┬─────────────┐
│ tpep_pickup_datetime │ tpep_dropoff_datetime │ passenger_count │ trip_distance │ RatecodeID │ PULocationID │ DOLocationID │ payment_type │ fare_amount │ extra  │ mta_tax │ tip_amount │ tolls_amount │ improvement_surcharge │ total_amount │ congestion_surcharge │ airport_fee │
│      timestamp       │       timestamp       │     double      │    double     │   double   │    int64     │    int64     │    int64     │   double    │ double │ double  │   double   │    double    │        double         │    double    │        double        │   double    │
├──────────────────────┼───────────────────────┼─────────────────┼───────────────┼────────────┼──────────────┼──────────────┼──────────────┼─────────────┼────────┼─────────┼────────────┼──────────────┼───────────────────────┼──────────────┼──────────────────────┼─────────────┤
│ 2022-01-01 00:35:40  │ 2022-01-01 00:53:29   │             2.0 │           3.8 │        1.0 │          142 │          236 │            1 │        14.5 │    3.0 │     0.5 │       3.65 │          0.0 │                   0.3 │        21.95 │                  2.5 │         0.0 │
│ 2022-01-01 00:33:43  │ 2022-01-01 00:42:07   │             1.0 │           2.1 │        1.0 │          236 │           42 │            1 │         8.0 │    0.5 │     0.5 │        4.0 │          0.0 │                   0.3 │         13.3 │                  0.0 │         0.0 │
│ 2022-01-01 00:53:21  │ 2022-01-01 01:02:19   │             1.0 │          0.97 │        1.0 │          166 │          166 │            1 │         7.5 │    0.5 │     0.5 │       1.76 │          0.0 │                   0.3 │        10.56 │                  0.0 │         0.0 │
│ 2022-01-01 00:25:21  │ 2022-01-01 00:35:23   │             1.0 │          1.09 │        1.0 │          114 │           68 │            2 │         8.0 │    0.5 │     0.5 │        0.0 │          0.0 │                   0.3 │         11.8 │                  2.5 │         0.0 │
│ 2022-01-01 00:36:48  │ 2022-01-01 01:14:20   │             1.0 │           4.3 │        1.0 │           68 │          163 │            1 │        23.5 │    0.5 │     0.5 │        3.0 │          0.0 │                   0.3 │         30.3 │                  2.5 │         0.0 │
│ 2022-01-01 00:40:15  │ 2022-01-01 01:09:48   │             1.0 │          10.3 │        1.0 │          138 │          161 │            1 │        33.0 │    3.0 │     0.5 │       13.0 │         6.55 │                   0.3 │        56.35 │                  2.5 │         0.0 │
│ 2022-01-01 00:20:50  │ 2022-01-01 00:34:58   │             1.0 │          5.07 │        1.0 │          233 │           87 │            1 │        17.0 │    0.5 │     0.5 │        5.2 │          0.0 │                   0.3 │         26.0 │                  2.5 │         0.0 │
│ 2022-01-01 00:13:04  │ 2022-01-01 00:22:45   │             1.0 │          2.02 │        1.0 │          238 │          152 │            2 │         9.0 │    0.5 │     0.5 │        0.0 │          0.0 │                   0.3 │         12.8 │                  2.5 │         0.0 │
│ 2022-01-01 00:30:02  │ 2022-01-01 00:44:49   │             1.0 │          2.71 │        1.0 │          166 │          236 │            1 │        12.0 │    0.5 │     0.5 │       2.25 │          0.0 │                   0.3 │        18.05 │                  2.5 │         0.0 │
│ 2022-01-01 00:48:52  │ 2022-01-01 00:53:28   │             1.0 │          0.78 │        1.0 │          236 │          141 │            2 │         5.0 │    0.5 │     0.5 │        0.0 │          0.0 │                   0.3 │          8.8 │                  2.5 │         0.0 │
│          ·           │          ·            │              ·  │            ·  │         ·  │           ·  │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │           ·  │                   ·  │          ·  │
│          ·           │          ·            │              ·  │            ·  │         ·  │           ·  │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │           ·  │                   ·  │          ·  │
│          ·           │          ·            │              ·  │            ·  │         ·  │           ·  │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │           ·  │                   ·  │          ·  │
│ 2022-01-01 02:08:42  │ 2022-01-01 02:10:55   │             5.0 │          0.38 │        1.0 │          107 │          164 │            2 │         3.5 │    0.5 │     0.5 │        0.0 │          0.0 │                   0.3 │          7.3 │                  2.5 │         0.0 │
│ 2022-01-01 02:15:32  │ 2022-01-01 02:24:50   │             5.0 │          2.17 │        1.0 │          107 │          246 │            2 │         9.0 │    0.5 │     0.5 │        0.0 │          0.0 │                   0.3 │         12.8 │                  2.5 │         0.0 │
│ 2022-01-01 02:34:10  │ 2022-01-01 02:38:07   │             5.0 │          0.58 │        1.0 │           68 │           90 │            2 │         4.5 │    0.5 │     0.5 │        0.0 │          0.0 │                   0.3 │          8.3 │                  2.5 │         0.0 │
│ 2022-01-01 02:44:37  │ 2022-01-01 03:01:53   │             5.0 │          4.37 │        1.0 │          249 │          263 │            1 │        15.5 │    0.5 │     0.5 │        2.0 │          0.0 │                   0.3 │         21.3 │                  2.5 │         0.0 │
│ 2022-01-01 02:10:55  │ 2022-01-01 02:20:02   │             2.0 │           1.9 │        1.0 │          163 │          263 │            1 │         8.5 │    0.5 │     0.5 │       2.46 │          0.0 │                   0.3 │        14.76 │                  2.5 │         0.0 │
│ 2022-01-01 02:35:49  │ 2022-01-01 02:49:01   │             2.0 │          2.03 │        1.0 │          162 │          107 │            1 │        10.0 │    0.5 │     0.5 │       1.38 │          0.0 │                   0.3 │        15.18 │                  2.5 │         0.0 │
│ 2022-01-01 02:02:51  │ 2022-01-01 02:26:00   │             4.0 │          17.2 │        2.0 │          132 │          233 │            1 │        52.0 │   3.75 │     0.5 │      15.75 │         6.55 │                   0.3 │        78.85 │                  2.5 │        1.25 │
│ 2022-01-01 02:05:48  │ 2022-01-01 02:15:02   │             1.0 │           2.7 │        1.0 │          170 │          262 │            1 │        10.0 │    3.0 │     0.5 │       2.75 │          0.0 │                   0.3 │        16.55 │                  2.5 │         0.0 │
│ 2022-01-01 02:25:55  │ 2022-01-01 02:36:09   │             2.0 │           3.3 │        1.0 │          141 │           41 │            1 │        11.5 │    3.0 │     0.5 │       3.05 │          0.0 │                   0.3 │        18.35 │                  2.5 │         0.0 │
│ 2022-01-01 02:29:39  │ 2022-01-01 02:53:36   │             1.0 │          5.17 │        1.0 │           48 │          223 │            1 │        19.0 │    0.5 │     0.5 │        0.0 │          0.0 │                   0.3 │         22.8 │                  2.5 │         0.0 │
└──────────────────────┴───────────────────────┴─────────────────┴───────────────┴────────────┴──────────────┴──────────────┴──────────────┴─────────────┴────────┴─────────┴────────────┴──────────────┴───────────────────────┴──────────────┴──────────────────────┴─────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                          17 columns

## Finding negative values in numeric fields

In [12]:
duckdb.sql("""
            SELECT 
            COUNT (*) AS total_rows,
            COUNT (*) FILTER (WHERE trip_distance < 0) AS negative_distance,
            COUNT (*) FILTER (WHERE fare_amount < 0) AS negative_fare,
            COUNT (*) FILTER (WHERE passenger_count < 0) AS negative_passengers,
            COUNT (*) FILTER (WHERE extra < 0) AS negative_extra,
            COUNT (*) FILTER (WHERE mta_tax < 0) AS negative_mta_tax,
            COUNT (*) FILTER (WHERE tip_amount < 0) AS negative_tip_amount,
            COUNT (*) FILTER (WHERE tolls_amount < 0) AS negative_tolls_amount,
            COUNT (*) FILTER (WHERE improvement_surcharge < 0) AS negative_improvement_surcharge,
            COUNT (*) FILTER (WHERE total_amount < 0) AS negative_total_amount,
            COUNT (*) FILTER (WHERE congestion_surcharge < 0) AS negative_congestion_surcharge,
            COUNT (*) FILTER (WHERE airport_fee < 0) AS negative_airport_fee
            FROM df
""").df()

,total_rows,negative_distance,negative_fare,negative_passengers,negative_extra,negative_mta_tax,negative_tip_amount,negative_tolls_amount,negative_improvement_surcharge,negative_total_amount,negative_congestion_surcharge,negative_airport_fee
0,167858646,0,4214194,0,1029414,1958014,8229,158379,2042089,2215654,1639288,344818

## Negative values

- Negative fare: `4214194`
- Negative extra: `1029414`
- Negative mta tax: `1958014`
- Negative tip amount: `8229`
- Negative tolls amount: `158379`
- Negative improvement surcharge: `2042089`
- Negative total amount: `2215654`
- Negative congestion surcharge: `1639288`
- Negative airport fee: `344818`

In [13]:
duckdb.sql("""
            SELECT * 
            FROM df
            WHERE 
            fare_amount < 0 
            
            """)

┌──────────────────────┬───────────────────────┬─────────────────┬───────────────┬────────────┬──────────────┬──────────────┬──────────────┬─────────────┬────────┬─────────┬────────────┬──────────────┬───────────────────────┬──────────────┬──────────────────────┬─────────────┐
│ tpep_pickup_datetime │ tpep_dropoff_datetime │ passenger_count │ trip_distance │ RatecodeID │ PULocationID │ DOLocationID │ payment_type │ fare_amount │ extra  │ mta_tax │ tip_amount │ tolls_amount │ improvement_surcharge │ total_amount │ congestion_surcharge │ airport_fee │
│      timestamp       │       timestamp       │     double      │    double     │   double   │    int64     │    int64     │    int64     │   double    │ double │ double  │   double   │    double    │        double         │    double    │        double        │   double    │
├──────────────────────┼───────────────────────┼─────────────────┼───────────────┼────────────┼──────────────┼──────────────┼──────────────┼─────────────┼────────┼─────────┼────────────┼──────────────┼───────────────────────┼──────────────┼──────────────────────┼─────────────┤
│ 2022-01-01 00:26:37  │ 2022-01-01 00:39:35   │             1.0 │          7.38 │        1.0 │          132 │          265 │            4 │       -21.0 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │       -23.55 │                  0.0 │       -1.25 │
│ 2022-01-01 00:27:18  │ 2022-01-01 00:40:50   │             1.0 │          5.14 │        1.0 │          152 │           48 │            4 │       -17.0 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │        -20.8 │                 -2.5 │         0.0 │
│ 2022-01-01 00:59:33  │ 2022-01-01 01:14:09   │             4.0 │          5.37 │        5.0 │           50 │          265 │            2 │       -75.0 │    0.0 │     0.0 │        0.0 │          0.0 │                  -0.3 │        -77.8 │                 -2.5 │         0.0 │
│ 2022-01-01 00:16:58  │ 2022-01-01 00:19:41   │             1.0 │          0.46 │        1.0 │           90 │          234 │            2 │        -4.0 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -7.8 │                 -2.5 │         0.0 │
│ 2022-01-01 00:29:12  │ 2022-01-01 00:40:29   │             1.0 │          3.13 │        1.0 │           13 │          246 │            4 │       -12.0 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │        -15.8 │                 -2.5 │         0.0 │
│ 2022-01-01 00:29:38  │ 2022-01-01 00:34:30   │             1.0 │          0.57 │        1.0 │          148 │           79 │            3 │        -5.0 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │       -10.05 │                 -2.5 │       -1.25 │
│ 2022-01-01 00:19:19  │ 2022-01-01 00:19:27   │             1.0 │           0.0 │        1.0 │          246 │          246 │            4 │        -2.5 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -6.3 │                 -2.5 │         0.0 │
│ 2022-01-01 00:51:36  │ 2022-01-01 00:51:57   │             1.0 │          0.11 │        1.0 │          264 │          238 │            4 │        -2.5 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -3.8 │                  0.0 │         0.0 │
│ 2022-01-01 00:45:02  │ 2022-01-01 01:18:12   │             3.0 │         10.16 │        1.0 │          170 │           61 │            4 │       -32.5 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │        -36.3 │                 -2.5 │         0.0 │
│ 2022-01-01 00:39:27  │ 2022-01-01 00:39:34   │             1.0 │           0.0 │        1.0 │          132 │          132 │            4 │        -2.5 │   -0.5 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -3.8 │                  0.0 │         0.0 │
│          ·           │          ·            │              ·  │            ·  │         ·  │           ·  │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │           ·  │                   ·  │          ·  │
│          ·           │          ·            │              ·  │            ·  │         ·  │           ·  │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │           ·  │                   ·  │          ·  │
│          ·           │          ·            │              ·  │            ·  │         ·  │           ·  │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │           ·  │                   ·  │          ·  │
│ 2022-01-25 12:02:36  │ 2022-01-25 12:03:24   │             1.0 │           0.0 │        1.0 │          260 │          260 │            4 │        -2.5 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -3.3 │                  0.0 │         0.0 │
│ 2022-01-25 12:32:19  │ 2022-01-25 12:32:35   │             1.0 │           0.0 │        2.0 │          162 │          162 │            4 │       -52.0 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │        -55.3 │                 -2.5 │         0.0 │
│ 2022-01-25 12:43:42  │ 2022-01-25 12:53:34   │             1.0 │          1.88 │        1.0 │           68 │          142 │            4 │        -9.0 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │        -12.3 │                 -2.5 │         0.0 │
│ 2022-01-25 12:21:55  │ 2022-01-25 12:33:55   │             1.0 │           5.7 │        1.0 │          170 │          107 │            4 │       -18.5 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │        -21.8 │                 -2.5 │         0.0 │
│ 2022-01-25 12:26:05  │ 2022-01-25 12:26:10   │             4.0 │           0.0 │        1.0 │          193 │          264 │            3 │        -2.5 │    0.0 │    -0.5 │       -0.2 │          0.0 │                  -0.3 │         -3.5 │                  0.0 │         0.0 │
│ 2022-01-25 12:34:18  │ 2022-01-25 12:34:32   │             1.0 │          0.01 │        1.0 │          163 │          163 │            3 │        -2.5 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -5.8 │                 -2.5 │         0.0 │
│ 2022-01-25 11:17:09  │ 2022-01-25 11:20:00   │             1.0 │          0.84 │        1.0 │           75 │          263 │            4 │        -4.5 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -7.8 │                 -2.5 │         0.0 │
│ 2022-01-25 12:57:28  │ 2022-01-25 13:05:01   │             2.0 │          0.81 │        1.0 │           68 │          186 │            4 │        -6.5 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -9.8 │                 -2.5 │         0.0 │
│ 2022-01-25 12:56:10  │ 2022-01-25 13:00:37   │             4.0 │           0.5 │        1.0 │          211 │          211 │            3 │        -4.5 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │         -7.8 │                 -2.5 │         0.0 │
│ 2022-01-25 12:42:30  │ 2022-01-25 12:55:48   │             1.0 │          0.61 │        1.0 │          263 │          263 │            4 │        -9.0 │    0.0 │    -0.5 │        0.0 │          0.0 │                  -0.3 │        -12.3 │                 -2.5 │         0.0 │
└──────────────────────┴───────────────────────┴─────────────────┴───────────────┴────────────┴──────────────┴──────────────┴──────────────┴─────────────┴────────┴─────────┴────────────┴──────────────┴───────────────────────┴──────────────┴──────────────────────┴─────────────┘
  ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                          17 columns

## Finding average passengers

In [19]:
duckdb.sql("""
            SELECT 
            AVG(trip_distance) AS average_trip_distance,
            MIN(trip_distance) AS minimum_trip_distance,
            MAX(trip_distance) AS maximum_trip_distance,
            PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY trip_distance) AS p25,
            PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY trip_distance) AS p50,
            PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY trip_distance) AS p75,
            PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY trip_distance) AS P99
            FROM df 
            """)

┌───────────────────────┬───────────────────────┬───────────────────────┬────────┬────────┬────────┬────────┐
│ average_trip_distance │ minimum_trip_distance │ maximum_trip_distance │  p25   │  p50   │  p75   │  P99   │
│        double         │        double         │        double         │ double │ double │ double │ double │
├───────────────────────┼───────────────────────┼───────────────────────┼────────┼────────┼────────┼────────┤
│     5.547781812859816 │                   0.0 │             398608.62 │   1.05 │   1.81 │    3.5 │   20.0 │
└───────────────────────┴───────────────────────┴───────────────────────┴────────┴────────┴────────┴────────┘

- The above analysis shows that 99 percent of the trips are under 20 miles.
- the maximum trip distance is 398608.62 (outlier)

In [30]:
duckdb.sql("""
            SELECT
            *
            FROM df
            WHERE trip_distance > 100
            """)

┌──────────────────────┬───────────────────────┬─────────────────┬───────────────┬────────────┬──────────────┬──────────────┬──────────────┬─────────────┬────────┬─────────┬────────────┬──────────────┬───────────────────────┬──────────────┬──────────────────────┬─────────────┐
│ tpep_pickup_datetime │ tpep_dropoff_datetime │ passenger_count │ trip_distance │ RatecodeID │ PULocationID │ DOLocationID │ payment_type │ fare_amount │ extra  │ mta_tax │ tip_amount │ tolls_amount │ improvement_surcharge │ total_amount │ congestion_surcharge │ airport_fee │
│      timestamp       │       timestamp       │     double      │    double     │   double   │    int64     │    int64     │    int64     │   double    │ double │ double  │   double   │    double    │        double         │    double    │        double        │   double    │
├──────────────────────┼───────────────────────┼─────────────────┼───────────────┼────────────┼──────────────┼──────────────┼──────────────┼─────────────┼────────┼─────────┼────────────┼──────────────┼───────────────────────┼──────────────┼──────────────────────┼─────────────┤
│ 2022-01-01 11:42:44  │ 2022-01-01 12:00:40   │             3.0 │         179.6 │        1.0 │          263 │          144 │            1 │        17.5 │    2.5 │     0.5 │       4.15 │          0.0 │                   0.3 │        24.95 │                  2.5 │         0.0 │
│ 2022-01-01 13:30:05  │ 2022-01-01 13:53:48   │             2.0 │         214.1 │        1.0 │          144 │            7 │            1 │        22.0 │    2.5 │     0.5 │       5.05 │          0.0 │                   0.3 │        30.35 │                  2.5 │         0.0 │
│ 2022-01-02 10:59:53  │ 2022-01-02 11:19:12   │             1.0 │         172.8 │        1.0 │          238 │          137 │            1 │        18.5 │    2.5 │     0.5 │        0.0 │          0.0 │                   0.3 │         21.8 │                  2.5 │         0.0 │
│ 2022-01-02 14:35:42  │ 2022-01-02 14:52:48   │             1.0 │         120.2 │        1.0 │          230 │           24 │            1 │        15.0 │    2.5 │     0.5 │        5.0 │          0.0 │                   0.3 │         23.3 │                  2.5 │         0.0 │
│ 2022-01-02 17:19:52  │ 2022-01-02 17:40:12   │             2.0 │         121.1 │        1.0 │          162 │           45 │            1 │        15.5 │    2.5 │     0.5 │        4.7 │          0.0 │                   0.3 │         23.5 │                  2.5 │         0.0 │
│ 2022-01-02 23:23:27  │ 2022-01-03 03:54:44   │             5.0 │        254.88 │        3.0 │          154 │          264 │            2 │       668.0 │    0.5 │     0.0 │        0.0 │         18.3 │                   0.3 │       688.35 │                  0.0 │        1.25 │
│ 2022-01-03 07:43:30  │ 2022-01-03 08:22:27   │             2.0 │         577.5 │        2.0 │          164 │          132 │            1 │        52.0 │    2.5 │     0.5 │       9.28 │         6.55 │                   0.3 │        71.13 │                  2.5 │         0.0 │
│ 2022-01-03 08:53:03  │ 2022-01-03 09:29:56   │             0.0 │         622.0 │        2.0 │          132 │          163 │            1 │        52.0 │   3.75 │     0.5 │       12.6 │         6.55 │                   0.3 │         75.7 │                  2.5 │        1.25 │
│ 2022-01-03 14:38:55  │ 2022-01-03 15:06:21   │             3.0 │         196.9 │        1.0 │           12 │          261 │            1 │        22.5 │    2.5 │     0.5 │        0.0 │          0.0 │                   0.3 │         25.8 │                  2.5 │         0.0 │
│ 2022-01-03 15:33:29  │ 2022-01-03 15:55:05   │             4.0 │         179.0 │        1.0 │           87 │          230 │            1 │        20.0 │    2.5 │     0.5 │       4.65 │          0.0 │                   0.3 │        27.95 │                  2.5 │         0.0 │
│          ·           │          ·            │              ·  │           ·   │         ·  │            · │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │          ·   │                   ·  │          ·  │
│          ·           │          ·            │              ·  │           ·   │         ·  │            · │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │          ·   │                   ·  │          ·  │
│          ·           │          ·            │              ·  │           ·   │         ·  │            · │           ·  │            · │          ·  │     ·  │      ·  │         ·  │           ·  │                    ·  │          ·   │                   ·  │          ·  │
│ 2025-12-30 19:22:00  │ 2025-12-30 19:33:00   │            NULL │     116899.98 │       NULL │          125 │          234 │            0 │       11.21 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        15.96 │                 NULL │        NULL │
│ 2025-12-30 22:49:00  │ 2025-12-30 22:58:00   │            NULL │       17002.0 │       NULL │          249 │          186 │            0 │       14.11 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        19.86 │                 NULL │        NULL │
│ 2025-12-30 22:46:00  │ 2025-12-30 22:53:00   │            NULL │      25108.95 │       NULL │          141 │          140 │            0 │        7.85 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        11.85 │                 NULL │        NULL │
│ 2025-12-31 10:46:00  │ 2025-12-31 10:53:00   │            NULL │     183825.81 │       NULL │            7 │          146 │            0 │       11.31 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        12.81 │                 NULL │        NULL │
│ 2025-12-31 10:05:00  │ 2025-12-31 10:12:00   │            NULL │     107138.08 │       NULL │          148 │           79 │            0 │         8.2 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        12.95 │                 NULL │        NULL │
│ 2025-12-31 16:00:00  │ 2025-12-31 17:00:00   │            NULL │      95310.01 │       NULL │          143 │          132 │            0 │       86.69 │    0.0 │     0.5 │       9.76 │         6.94 │                   1.0 │       107.39 │                 NULL │        NULL │
│ 2025-12-31 17:30:00  │ 2025-12-31 18:15:00   │            NULL │      92140.64 │       NULL │           82 │          188 │            0 │       46.82 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        48.32 │                 NULL │        NULL │
│ 2025-12-31 18:40:00  │ 2025-12-31 18:55:00   │            NULL │     139278.22 │       NULL │           50 │           90 │            0 │       24.75 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │         29.5 │                 NULL │        NULL │
│ 2025-12-31 19:48:00  │ 2025-12-31 20:09:00   │            NULL │     221055.79 │       NULL │           33 │           68 │            0 │       29.93 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        38.14 │                 NULL │        NULL │
│ 2025-12-31 23:02:00  │ 2025-12-31 23:15:00   │            NULL │      85608.56 │       NULL │          151 │           74 │            0 │       26.08 │    0.0 │     0.5 │        0.0 │          0.0 │                   1.0 │        27.58 │                 NULL │        NULL │
└──────────────────────┴───────────────────────┴─────────────────┴───────────────┴────────────┴──────────────┴──────────────┴──────────────┴─────────────┴────────┴─────────┴────────────┴──────────────┴───────────────────────┴──────────────┴──────────────────────┴─────────────┘
  7316 rows (20 shown)                                                                                                                                                                                                                                                   17 columns

## Extracting Trip Distance Time

In [33]:
duckdb.sql("""
            SELECT 
                trip_distance,
                EXTRACT(EPOCH FROM (
                    tpep_dropoff_datetime - tpep_pickup_datetime
                    )) / 60 AS trip_duration_minutes,
                    fare_amount,
                    total_amount
            FROM df
            WHERE trip_distance > 20
            ORDER BY trip_distance DESC
            """).df()

         trip_distance  trip_duration_minutes  fare_amount  total_amount
0            398608.62              14.000000        22.04         26.04
1            397994.37              18.000000        21.97         23.47
2            389678.46              13.000000        12.11         18.83
3            386088.43              20.000000        17.16         21.91
4            366343.04              35.000000        22.06         26.06
...                ...                    ...          ...           ...
1677976          20.01              34.400000        95.80        122.63
1677977          20.01              72.300000        88.40        109.63
1677978          20.01              50.900000        70.00         99.23
1677979          20.01              38.566667        97.20        130.58
1677980          20.01              68.900000        70.00        104.88

[1677981 rows x 4 columns]

## References

- https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf
- https://duckdb.org/docs/current/clients/python/overview